### ISSUE TITLE
[BUG] Unable to Install

### ISSUE THREAD

**Issue by GhostwheelX** [IsThisMyRealName/too-many-tokens-dnd#1]
When attempting to install from the listed URL (https://github.com/IsThisMyRealName/too-many-tokens-dnd/releases/download/BigRelease/module.json) the following error is received:
![image](https://github.com/IsThisMyRealName/too-many-tokens-dnd/assets/68725723/74f349ad-4f1a-4443-9472-44c81409f1fe)

**Comment by PhillypHenning** [comment]
I'm having the same issue as the above

**Comment by willgvfranco** [comment]
Same here
