### ISSUE TITLE
Backwards compability: removed images in next releases

### ISSUE THREAD

**Issue by karpiq24** [IsThisMyRealName/too-many-tokens-dnd#2]
It would be nice to maintain backwards compatibility and keep the same paths if images are upgraded.
I had already placed bandits and after an update their randomly selected tokens disappeared and I had to reselect them.

**Comment by IsThisMyRealName** [comment]
I will include a macro in the next version to automatically reassign images for tokens.
The same paths will not always be possible, since sometimes they will be improved upon or will not make sense with a new image version.

**Comment by karpiq24** [comment]
This is a nice solution. Thank you for your work, this is an amazing module.

**Comment by IsThisMyRealName** [comment]
Added the macro in 1.0.6.
Please open a new issue if there are any problems.
