### ISSUE TITLE
New Macro doesnt appear in the compendium.

### ISSUE THREAD

**Issue by Silvestrae** [IsThisMyRealName/too-many-tokens-dnd#3]
As title.
New macro isn't in the compendium, its just an empty compendium.

![image](https://github.com/IsThisMyRealName/too-many-tokens-dnd/assets/55987580/7a5df17e-8009-43ce-b6eb-4c1b540054ff)
![image](https://github.com/IsThisMyRealName/too-many-tokens-dnd/assets/55987580/8880937b-c779-4d83-a2ea-ad5e5a24c16c)

**Comment by IsThisMyRealName** [comment]
Thank you for the feedback. I thought I did it correctly. Still figuring stuff out. I will (hopefully) get it to appear in the next update.
Until then you can find it as a .ja file in the module folder.
Sorry for the inconvenience.

**Comment by Silvestrae** [comment]
Yep, I did see it in the module and am using it successfully (great macro btw), just thought id let you know about the compendium 😉

**Comment by IsThisMyRealName** [comment]
I guess the problem was that I set the macro to be for 5e only. I now set it to be available for any system. Is your world pathfinder/not 5e? Does it work with the newest update? If so I will close this issue. Hope it helps. :)
