### ISSUE TITLE
[Feature request] Allow the macro to randomize unknown or renamed creatures

### ISSUE THREAD

**Issue by mcabel** [IsThisMyRealName/too-many-tokens-dnd#4]
When a creature is renamed, the macro wont recognize it, and will not allow randomization of the token.

![image](https://github.com/IsThisMyRealName/too-many-tokens-dnd/assets/10392829/89b05d35-5bad-4a05-b98a-857193ad3372)

My request is that on such situations the macro will bring a dialogue with creature types, and if I click humanoid, it will make the token image humanoid. If I click dragon, it will make it into a dragon; Regardless of the token name.

**Comment by IsThisMyRealName** [comment]
Added new macro to todays version. Thank you for the suggestion. :D
