### ISSUE TITLE
[Feature Request] Too Many Portraits

### ISSUE THREAD

**Issue by kaerosd** [IsThisMyRealName/too-many-tokens-dnd#5]
Sooo, just throwing this out there. You have the full databank of the base images for all of the tokens, why not include them and have them sub in as the 'portrait' for the token in question as well? Having them matched up would be really nice.

**Comment by IsThisMyRealName** [comment]
I like the idea. Sadly the base images are larger in size (3,5 GB to 0,5 GB) and not categorized the same way. Changing that now is not my priority. I did however add a button to the macro to automatically apply a "too many token" as the actor portrait when changing the wildcard for an actor. I hope that helps.
